project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework_swagger.views import get_swagger_view
from rest_framework.documentation import include_docs_urls
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
import debug_toolbar
from apps.restful.views import TestView

API_TITLE = 'EBOT API'
API_DESCRIPTION = 'A Web API for ebot.'

yasg_schema_view = get_schema_view(
    openapi.Info(
        title=API_TITLE,
        default_version='v1',
        description=API_DESCRIPTION,
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="techschool@info.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

schema_view = get_swagger_view(title=API_TITLE)

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('apps.bot.urls')),
    path('v1/', include('apps.restful.urls')),
    path('docs/', include_docs_urls(title=API_TITLE, description=API_DESCRIPTION)),
    path('swagger/', yasg_schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('', include('apps.payment.urls')),
    path('click/transaction/', TestView.as_view()),
    path('schema/view/', schema_view),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/main/models.py
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.mail import send_mail
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.utils.text import gettext_lazy as _
from django.conf import settings
from apps.main.managers import UserManager

__all__ = ['Chat', 'Subject', 'Class', 'Section', 'Topic', 'Question', 'Order', 'OrderItem', 'Variant',
           'Transaction', 'Group', 'CustomUser', 'ExtraData', 'Withdraw', 'QuestionSetting', 'QuestionLevel',
           'Solution', 'PaymentHistory', ]


class ExtraData:
    STATE_CENTER_TEST = 'state_center_test'
    SUBJECTED_TEST = 'subjected_test'

    TEST_FORMATS = (
        (STATE_CENTER_TEST, "DTM test"),
        (SUBJECTED_TEST, "Subjected test"),
    )
    ADMIN = 'admin'
    ENTRANT = 'entrant'
    MENTOR = 'mentor'
    MODERATOR = 'moderator'
    USER_TYPES = (
        (ENTRANT, "Entrant"),
        (MENTOR, "Mentor"),
        (MODERATOR, 'Moderator'),
        (ADMIN, 'Admin'),
    )
    WELCOME_MENU = "welcome"
    USER_TYPE_MENU = "user_type"
    ENTRANT_MENU = "entrant"
    TEST_FORMAT_MENU = "test_format"
    BLOCK_SUBJECTS_MENU = "block_subjects"
    BLOCK_SUBJECTS_ORDER_CONFIRM_MENU = "block_subjects_order_confirm"
    BLOCK_SUBJECTS_ORDER_NOT_ENOUGH_MONEY_MENU = "block_subjects_order_not_enough_money"
    BLOCK_SUBJECTS_ORDER_FILE_MENU = "block_subjects_order_file"
    CHOOSE_SUBJECTS_MENU = "choose_subjects"
    CHOOSE_SECTIONS_MENU = "choose_sections"
    CHOOSE_CLASS_MENU = "choose_class"
    CHOOSE_TOPICS_MENU = "choose_topics"
    SUBJECT_TEST_ORDER_CONFIRM_MENU = "subjected_test_order_confirm"
    NOT_SUBJECT_TEST_ORDER_CONFIRM_MENU = "not_subjected_test_order_confirm"
    MY_ORDERS_MENU = "my_orders"
    FILLING_BALANCE_MENU = "filling_balance"
    MY_BALANCE_MENU = "my_balance"
    CHOOSE_PAYMENT_METHOD_MENU = "choose_payment_method"
    MY_SETTINGS_MENU = "my_settings"
    CHANGE_PHONE_MENU = "change_phone"
    CHANGE_NAME_MENU = "change_name"
    MY_RESULTS_MENU = "my_results"
    MENTOR_MENU = "mentor"
    ADD_GROUP = "add_group"
    SELECTED_GROUP = "selected_group"
    STATISTIC_VIEW = "statistic_view"
    STUDEND_CONTROL = "student_control"
    CHECK_RESULT = 'check_result'

    STEPS = (
        (WELCOME_MENU, "Welcome menu"),
        (USER_TYPE_MENU, "User type menu"),
        (ENTRANT_MENU, "Entrant menu"),
        (TEST_FORMAT_MENU, "Test format menu"),
        (BLOCK_SUBJECTS_MENU, "Block subjects menu"),
        (BLOCK_SUBJECTS_ORDER_CONFIRM_MENU, "Block subjects order confirm menu"),
        (BLOCK_SUBJECTS_ORDER_NOT_ENOUGH_MONEY_MENU, "Block subjects order not enough money menu"),
        (BLOCK_SUBJECTS_ORDER_FILE_MENU, "Block subjects order file menu"),
        (CHOOSE_SUBJECTS_MENU, "Choose subjects"),
        (CHOOSE_SECTIONS_MENU, "Choose sections"),
        (CHOOSE_CLASS_MENU, "Choose class"),
        (CHOOSE_TOPICS_MENU, "Choose topics"),
        (MY_ORDERS_MENU, "My orders"),
        (FILLING_BALANCE_MENU, "Filling balance"),
        (MY_BALANCE_MENU, "My balance"),
        (CHOOSE_PAYMENT_METHOD_MENU, "Choose payment_old method"),
        (MY_SETTINGS_MENU, "My settings"),
        (CHANGE_PHONE_MENU, "Change phone"),
        (CHANGE_NAME_MENU, "Change name"),
        (MY_RESULTS_MENU, "My results"),
        (MENTOR_MENU, "Mentor menu"),
        (ADD_GROUP, "Add group"),
        (SELECTED_GROUP, "Selected group"),
        (STATISTIC_VIEW, "Statistic view"),
        (STUDEND_CONTROL, "Student Control"),
        (CHECK_RESULT, "Check result"),
    )


class CustomUser(AbstractUser):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.

    Username and password are required. Other fields are optional.
    """
    username_validator = UnicodeUsernameValidator()
    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    phone = models.CharField(
        max_length=60,
        null=True,
        blank=True,
        unique=True,
        error_messages={
            'unique': _("A user with that phone already exists.")
        },
    )
    email = models.EmailField(_('email address'), blank=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    type_of_user = models.CharField(choices=ExtraData.USER_TYPES, null=True, max_length=150)

    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    balance = models.FloatField(default=0)
    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def get_phone(self):
        return str(self.phone).replace("+998", "")


class Chat(models.Model, ExtraData):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)
    user_type = models.CharField(max_length=250, choices=ExtraData.USER_TYPES, default=ExtraData.ENTRANT)
    chat_id = models.IntegerField(null=True)
    first_name = models.CharField(null=True, max_length=250, blank=True)
    last_name = models.CharField(null=True, max_length=250, blank=True)
    username = models.CharField(null=True, max_length=250, blank=True)
    phone = models.CharField(null=True, max_length=250, blank=True, unique=True)
    is_active = models.BooleanField(default=True)
    selected_test_format = models.CharField(max_length=25, choices=ExtraData.TEST_FORMATS, null=True, blank=True)
    selected_subjects = models.ManyToManyField('Subject', blank=True)
    selected_topics = models.ManyToManyField('Topic', blank=True)
    selected_classes = models.ManyToManyField('Class', blank=True)
    groups = models.ManyToManyField('Group', blank=True, related_name="chats")
    would_like_mandatory_tests = models.BooleanField(null=True, blank=True)
    step = models.CharField(max_length=255, choices=ExtraData.STEPS, null=True, blank=True)
    balance = models.FloatField(default=0)
    page = models.IntegerField(default=0)
    payment_amount = models.IntegerField(default=0)
    answer = models.CharField(max_length=250, blank=True, null=True)

    def __str__(self):
        if self.first_name or self.last_name:
            return "{} {}".format(self.first_name, self.last_name)
        elif self.username:
            return self.username
        elif self.phone:
            return self.phone
        return '<Chat {}>'.format(self.chat_id)

    def clear(self):
        self.selected_test_format = ''
        self.selected_subjects.clear()
        self.selected_classes.clear()
        self.selected_topics.clear()
        self.would_like_mandatory_tests = False
        self.save()

    def set_step(self, step):
        self.step = step
        self.save()

    def make_payment_for(self, order):
        self.balance -= float(order.total_price)
        self.save()
        PaymentHistory(chat=self, amount=order.total_price, order=order).save()
        order.is_paid = True
        order.save()


class Subject(models.Model):
    title = models.CharField(max_length=250)
    is_thematic = models.BooleanField(default=False)
    is_mandatory_block_subject = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Class(models.Model):
    title = models.CharField(max_length=250)

    class Meta:
        verbose_name = 'Class'
        verbose_name_plural = 'Classes'

    def __str__(self):
        return self.title


class Group(models.Model):
    title = models.CharField(max_length=25)
    students = models.ManyToManyField(Chat, blank=True, related_name='group')
    statistic = models.FileField(null=True)

    def __str__(self):
        return self.title


class Section(models.Model):
    title = models.CharField(max_length=250)
    subject = models.ForeignKey(Subject, null=True, on_delete=models.CASCADE, related_name="sections")

    def __str__(self):
        return self.title


class Topic(models.Model):
    title = models.CharField(max_length=250)
    section = models.ForeignKey(Section, null=True, on_delete=models.CASCADE, related_name="topics", blank=True)
    subject = models.ForeignKey(Subject, null=True, on_delete=models.CASCADE, related_name="topics", blank=True)
    _class = models.ForeignKey(Class, null=True, on_delete=models.CASCADE, related_name="topics", blank=True)

    def __str__(self):
        return self.title


class Question(models.Model):

templates/pdf/dtm.html
{% load pdf_extras %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>DTM testi</title>
    <link rel="stylesheet" href="http://127.0.0.1:8000/static/css/style.css" media="all"/>
    <style>
        .page-breaker {
            page-break-before: always;
        }
    </style>
</head>
<body>
<table style="width: 100%">
    {% for order_item in order.items.all %}
        <tr class="header page-breaker">
            <th colspan="4">{{ order_item.subject.title }} fanidan savollar</th>
        </tr>
        {% for question_item in order_item.order_items.all %}
            <tr>
                <td colspan="4">{{ forloop.counter }}. {{ question_item.question.description }}</td>
            </tr>
            <tr>
                {% for variant in question_item.question.variants.all %}
                    <td>{{ variant.get_title_display }}) {{ variant.description|safe|replace_with_svg }}</td>
                {% endfor %}
            </tr>
        {% endfor %}
    {% endfor %}
</table>
</body>
</html>

templates/pdf/preview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>784-savol uchun D-variant:</p><p><svg xmlns:xlink="http://www.w3.org/1999/xlink" width="28.102ex" height="4.676ex" style="vertical-align: -2.005ex;" viewBox="0 -1150.1 12099.4 2013.3" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg" aria-labelledby="MathJax-SVG-1-Title">
<title id="MathJax-SVG-1-Title">Equation</title>
<defs aria-hidden="true">
<path stroke-width="1" id="E4-MJSZ1-222B" d="M113 -244Q113 -246 119 -251T139 -263T167 -269Q186 -269 199 -260Q220 -247 232 -218T251 -133T262 -15T276 155T297 367Q300 390 305 438T314 512T325 580T340 647T361 703T390 751T428 784T479 804Q481 804 488 804T501 805Q552 802 581 769T610 695Q610 669 594 657T561 645Q542 645 527 658T512 694Q512 705 516 714T526 729T538 737T548 742L552 743Q552 745 545 751T525 762T498 768Q475 768 460 756T434 716T418 652T407 559T398 444T387 300T369 133Q349 -38 337 -102T303 -207Q256 -306 169 -306Q119 -306 87 -272T55 -196Q55 -170 71 -158T104 -146Q123 -146 138 -159T153 -195Q153 -206 149 -215T139 -230T127 -238T117 -242L113 -244Z"></path>
<path stroke-width="1" id="E4-MJMAIN-32" d="M109 429Q82 429 66 447T50 491Q50 562 103 614T235 666Q326 666 387 610T449 465Q449 422 429 383T381 315T301 241Q265 210 201 149L142 93L218 92Q375 92 385 97Q392 99 409 186V189H449V186Q448 183 436 95T421 3V0H50V19V31Q50 38 56 46T86 81Q115 113 136 137Q145 147 170 174T204 211T233 244T261 278T284 308T305 340T320 369T333 401T340 431T343 464Q343 527 309 573T212 619Q179 619 154 602T119 569T109 550Q109 549 114 549Q132 549 151 535T170 489Q170 464 154 447T109 429Z"></path>
<path stroke-width="1" id="E4-MJMAIN-31" d="M213 578L200 573Q186 568 160 563T102 556H83V602H102Q149 604 189 617T245 641T273 663Q275 666 285 666Q294 666 302 660V361L303 61Q310 54 315 52T339 48T401 46H427V0H416Q395 3 257 3Q121 3 100 0H88V46H114Q136 46 152 46T177 47T193 50T201 52T207 57T213 61V578Z"></path>
<path stroke-width="1" id="E4-MJMAIN-33" d="M127 463Q100 463 85 480T69 524Q69 579 117 622T233 665Q268 665 277 664Q351 652 390 611T430 522Q430 470 396 421T302 350L299 348Q299 347 308 345T337 336T375 315Q457 262 457 175Q457 96 395 37T238 -22Q158 -22 100 21T42 130Q42 158 60 175T105 193Q133 193 151 175T169 130Q169 119 166 110T159 94T148 82T136 74T126 70T118 67L114 66Q165 21 238 21Q293 21 321 74Q338 107 338 175V195Q338 290 274 322Q259 328 213 329L171 330L168 332Q166 335 166 348Q166 366 174 366Q202 366 232 371Q266 376 294 413T322 525V533Q322 590 287 612Q265 626 240 626Q208 626 181 615T143 592T132 580H135Q138 579 143 578T153 573T165 566T175 555T183 540T186 520Q186 498 172 481T127 463Z"></path>
<path stroke-width="1" id="E4-MJMAIN-64" d="M376 495Q376 511 376 535T377 568Q377 613 367 624T316 637H298V660Q298 683 300 683L310 684Q320 685 339 686T376 688Q393 689 413 690T443 693T454 694H457V390Q457 84 458 81Q461 61 472 55T517 46H535V0Q533 0 459 -5T380 -11H373V44L365 37Q307 -11 235 -11Q158 -11 96 50T34 215Q34 315 97 378T244 442Q319 442 376 393V495ZM373 342Q328 405 260 405Q211 405 173 369Q146 341 139 305T131 211Q131 155 138 120T173 59Q203 26 251 26Q322 26 373 103V342Z"></path>
<path stroke-width="1" id="E4-MJMATHI-78" d="M52 289Q59 331 106 386T222 442Q257 442 286 424T329 379Q371 442 430 442Q467 442 494 420T522 361Q522 332 508 314T481 292T458 288Q439 288 427 299T415 328Q415 374 465 391Q454 404 425 404Q412 404 406 402Q368 386 350 336Q290 115 290 78Q290 50 306 38T341 26Q378 26 414 59T463 140Q466 150 469 151T485 153H489Q504 153 504 145Q504 144 502 134Q486 77 440 33T333 -11Q263 -11 227 52Q186 -10 133 -10H127Q78 -10 57 16T35 71Q35 103 54 123T99 143Q142 143 142 101Q142 81 130 66T107 46T94 41L91 40Q91 39 97 36T113 29T132 26Q168 26 194 71Q203 87 217 139T245 247T261 313Q266 340 266 352Q266 380 251 392T217 404Q177 404 142 372T93 290Q91 281 88 280T72 278H58Q52 284 52 289Z"></path>
<path stroke-width="1" id="E4-MJMAIN-2B" d="M56 237T56 250T70 270H369V420L370 570Q380 583 389 583Q402 583 409 568V270H707Q722 262 722 250T707 230H409V-68Q401 -82 391 -82H389H387Q375 -82 369 -68V230H70Q56 237 56 250Z"></path>
<path stroke-width="1" id="E4-MJMAIN-2202" d="M202 508Q179 508 169 520T158 547Q158 557 164 577T185 624T230 675T301 710L333 715H345Q378 715 384 714Q447 703 489 661T549 568T566 457Q566 362 519 240T402 53Q321 -22 223 -22Q123 -22 73 56Q42 102 42 148V159Q42 276 129 370T322 465Q383 465 414 434T455 367L458 378Q478 461 478 515Q478 603 437 639T344 676Q266 676 223 612Q264 606 264 572Q264 547 246 528T202 508ZM430 306Q430 372 401 400T333 428Q270 428 222 382Q197 354 183 323T150 221Q132 149 132 116Q132 21 232 21Q244 21 250 22Q327 35 374 112Q389 137 409 196T430 306Z"></path>
<path stroke-width="1" id="E4-MJMAIN-34" d="M462 0Q444 3 333 3Q217 3 199 0H190V46H221Q241 46 248 46T265 48T279 53T286 61Q287 63 287 115V165H28V211L179 442Q332 674 334 675Q336 677 355 677H373L379 671V211H471V165H379V114Q379 73 379 66T385 54Q393 47 442 46H471V0H462ZM293 211V545L74 212L183 211H293Z"></path>
<path stroke-width="1" id="E4-MJMAIN-6C" d="M42 46H56Q95 46 103 60V68Q103 77 103 91T103 124T104 167T104 217T104 272T104 329Q104 366 104 407T104 482T104 542T103 586T103 603Q100 622 89 628T44 637H26V660Q26 683 28 683L38 684Q48 685 67 686T104 688Q121 689 141 690T171 693T182 694H185V379Q185 62 186 60Q190 52 198 49Q219 46 247 46H263V0H255L232 1Q209 2 183 2T145 3T107 3T57 1L34 0H26V46H42Z"></path>
<path stroke-width="1" id="E4-MJMAIN-69" d="M69 609Q69 637 87 653T131 669Q154 667 171 652T188 609Q188 579 171 564T129 549Q104 549 87 564T69 609ZM247 0Q232 3 143 3Q132 3 106 3T56 1L34 0H26V46H42Q70 46 91 49Q100 53 102 60T104 102V205V293Q104 345 102 359T88 378Q74 385 41 385H30V408Q30 431 32 431L42 432Q52 433 70 434T106 436Q123 437 142 438T171 441T182 442H185V62Q190 52 197 50T232 46H255V0H247Z"></path>
<path stroke-width="1" id="E4-MJMAIN-6D" d="M41 46H55Q94 46 102 60V68Q102 77 102 91T102 122T103 161T103 203Q103 234 103 269T102 328V351Q99 370 88 376T43 385H25V408Q25 431 27 431L37 432Q47 433 65 434T102 436Q119 437 138 438T167 441T178 442H181V402Q181 364 182 364T187 369T199 384T218 402T247 421T285 437Q305 442 336 442Q351 442 364 440T387 434T406 426T421 417T432 406T441 395T448 384T452 374T455 366L457 361L460 365Q463 369 466 373T475 384T488 397T503 410T523 422T546 432T572 439T603 442Q729 442 740 329Q741 322 741 190V104Q741 66 743 59T754 49Q775 46 803 46H819V0H811L788 1Q764 2 737 2T699 3Q596 3 587 0H579V46H595Q656 46 656 62Q657 64 657 200Q656 335 655 343Q649 371 635 385T611 402T585 404Q540 404 506 370Q479 343 472 315T464 232V168V108Q464 78 465 68T468 55T477 49Q498 46 526 46H542V0H534L510 1Q487 2 460 2T422 3Q319 3 310 0H302V46H318Q379 46 379 62Q380 64 380 200Q379 335 378 343Q372 371 358 385T334 402T308 404Q263 404 229 370Q202 343 195 315T187 232V168V108Q187 78 188 68T191 55T200 49Q221 46 249 46H265V0H257L234 1Q210 2 183 2T145 3Q42 3 33 0H25V46H41Z"></path>
<path stroke-width="1" id="E4-MJMAIN-2192" d="M56 237T56 250T70 270H835Q719 357 692 493Q692 494 692 496T691 499Q691 511 708 511H711Q720 511 723 510T729 506T732 497T735 481T743 456Q765 389 816 336T935 261Q944 258 944 250Q944 244 939 241T915 231T877 212Q836 186 806 152T761 85T740 35T732 4Q730 -6 727 -8T711 -11Q691 -11 691 0Q691 7 696 25Q728 151 835 230H70Q56 237 56 250Z"></path>
<path stroke-width="1" id="E4-MJMAIN-221E" d="M55 217Q55 305 111 373T254 442Q342 442 419 381Q457 350 493 303L507 284L514 294Q618 442 747 442Q833 442 888 374T944 214Q944 128 889 59T743 -11Q657 -11 580 50Q542 81 506 128L492 147L485 137Q381 -11 252 -11Q166 -11 111 57T55 217ZM907 217Q907 285 869 341T761 397Q740 397 720 392T682 378T648 359T619 335T594 310T574 285T559 263T548 246L543 238L574 198Q605 158 622 138T664 94T714 61T765 51Q827 51 867 100T907 217ZM92 214Q92 145 131 89T239 33Q357 33 456 193L425 233Q364 312 334 337Q285 380 233 380Q171 380 132 331T92 214Z"></path>
<path stroke-width="1" id="E4-MJSZ1-220F" d="M158 656Q147 684 131 694Q110 707 69 710H55V750H888V710H874Q840 708 820 698T795 678T786 656V-155Q798 -206 874 -210H888V-250H570V-210H584Q618 -208 638 -197T663 -178T673 -155V710H270V277L271 -155Q283 -206 359 -210H373V-250H55V-210H69Q103 -208 123 -197T148 -178T158 -155V656Z"></path>
</defs>
<g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)" aria-hidden="true">
 <use xlink:href="#E4-MJSZ1-222B" x="0" y="0"></use>
 <use transform="scale(0.707)" xlink:href="#E4-MJMAIN-32" x="921" y="754"></use>
 <use transform="scale(0.707)" xlink:href="#E4-MJMAIN-31" x="668" y="-484"></use>
 <use xlink:href="#E4-MJMAIN-33" x="1272" y="0"></use>
 <use xlink:href="#E4-MJMAIN-64" x="1939" y="0"></use>
 <use xlink:href="#E4-MJMATHI-78" x="2662" y="0"></use>
 <use xlink:href="#E4-MJMAIN-2B" x="3485" y="0"></use>
<g transform="translate(4430,0)">
<g transform="translate(286,0)">
<rect stroke="none" width="849" height="60" x="0" y="220"></rect>
<g transform="translate(60,460)">
 <use transform="scale(0.707)" xlink:href="#E4-MJMAIN-2202" x="0" y="0"></use>
 <use transform="scale(0.707)" xlink:href="#E4-MJMAIN-33" x="531" y="0"></use>
</g>
<g transform="translate(60,-451)">
 <use transform="scale(0.707)" xlink:href="#E4-MJMAIN-2202" x="0" y="0"></use>
 <use transform="scale(0.707)" xlink:href="#E4-MJMAIN-34" x="531" y="0"></use>
</g>
</g>
</g>
 <use xlink:href="#E4-MJMAIN-2B" x="5937" y="0"></use>
<g transform="translate(7049,0)">
<g transform="translate(366,0)">
 <use xlink:href="#E4-MJMAIN-6C"></use>
 <use xlink:href="#E4-MJMAIN-69" x="278" y="0"></use>
 <use xlink:href="#E4-MJMAIN-6D" x="557" y="0"></use>
</g>
<g transform="translate(0,-640)">
 <use transform="scale(0.707)" xlink:href="#E4-MJMAIN-32"></use>
 <use transform="scale(0.707)" xlink:href="#E4-MJMAIN-32" x="500" y="0"></use>
 <use transform="scale(0.707)" xlink:href="#E4-MJMAIN-2192" x="1001" y="0"></use>
 <use transform="scale(0.707)" xlink:href="#E4-MJMAIN-221E" x="2001" y="0"></use>
</g>
</g>
 <use xlink:href="#E4-MJMAIN-2B" x="9588" y="0"></use>
<g transform="translate(10700,0)">
 <use xlink:href="#E4-MJSZ1-220F" x="0" y="0"></use>
 <use transform="scale(0.707)" xlink:href="#E4-MJMAIN-31" x="1335" y="675"></use>
 <use transform="scale(0.707)" xlink:href="#E4-MJMAIN-31" x="1335" y="-405"></use>
</g>
</g>
</svg>
</p>
</body>
</html>